### ISSUE TITLE
pypi links are broken

### ISSUE THREAD

**Issue by bmannix** [fcurella/cookiejar#1]
Running latest version of pip, I cannot install cookiejar

bmannix-ws:~ bmannix $ pip --version
pip 1.5.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
bmannix-ws:~ bmannix $ pip search cookiejar
firefox_jar               - Load firefox cookies to CookieJar (requests compatible format).
cookiejar                 - Cookiecutter templates discovery and management.
bmannix-ws:~ bmannix $ pip install cookiejar
Downloading/unpacking cookiejar
  Could not find any downloads that satisfy the requirement cookiejar
Cleaning up...
No distributions at all found for cookiejar
Storing debug log for failure in /home/bmannix/.pip/pip.log

**Comment by fcurella** [comment]
@bmannix I've just released `v0.0.2`
